generator:
  class: sfPropelGenerator
  param:
    model_class:           BidSitio
    theme:                 adminBS
    non_verbose_templates: true
    with_show:             false
    singular:              BidSitio
    plural:                BidSitios
    route_prefix:          bid_sitio
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Sitios
        batch_actions: {}
        object_actions: {}
        display:
          - =nombre
      filter:  
        display:
          - nombre
          - area_protegida
      form:    ~
      edit:    
        title: Modificar sitio
      new:     
        title: Agregar sitio
