<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_conteo_indicador' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidConteoIndicadorQuery extends BaseBidConteoIndicadorQuery {
/*
    public function soloAnppv() {
        return $this->useBidSitioQuery()->filterByAreaProtegida(ProjectConfiguration::ANPPV)->endUse();
    }

    public function soloPimcpa() {
        return $this->useBidSitioQuery()->filterByAreaProtegida(ProjectConfiguration::PIMCPA)->endUse();
    }
    */
    public function soloAvesPlayerasPimcpa() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::AVES_PALYERAS_PIMCPA);
    }
    public function soloAvesPlayerasAnppv() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::AVES_PALYERAS_ANPPV);
    }
    public function soloMamiferosCarnivoros() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::MAMIFEROS_CARNIVOROS);
    }
    public function ci1()
    {
        return $this->soloAvesPlayerasPimcpa()->select(array(
            'q','m','y',
            'especie',
            'especie_id',
            'cantidad'
        ))
        ->withColumn('especie_id','especie_id')
        ->withColumn('sum(cantidad)','cantidad')
        ->withColumn("date_part( 'year', fecha)",'y')
        ->withColumn("date_part( 'month', fecha)",'m')
        ->withColumn("case when date_part( 'day', fecha)<16 then 1  else 2 end",'q')
        ->useBidEspecieQuery()
        ->orderByNombre()
        ->groupByNombre()->withColumn('bid_especie.nombre','especie')
        ->endUse()
        ->groupByEspecieId()
        ->groupBy('y')
        ->groupBy('m')
        ->groupBy('q')
        ->orderBy('y')
        ->orderBy('m')
        ->orderBy('q')
        ;
        
    }
} // BidConteoIndicadorQuery
