<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_conteo_indicador' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidConteoIndicadorPeer extends BaseBidConteoIndicadorPeer {

    public static $indicadores=array(
        self::AVES_PALYERAS_PIMCPA=>'Aves playeras P.I.M.C.P.A.',
        self::AVES_PALYERAS_ANPPV=>'Aves playeras A.N.P.P.V.',
        self::MAMIFEROS_CARNIVOROS=>'Mamíferos carnívoros A.N.P.P.V.'
    );
    
    const AVES_PALYERAS_PIMCPA=4;
    const AVES_PALYERAS_ANPPV=5;
    const MAMIFEROS_CARNIVOROS=7;
} // BidConteoIndicadorPeer
