<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_conteo_indicador' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidConteoIndicadorQuery extends BaseBidConteoIndicadorQuery {
/*
    public function soloAnppv() {
        return $this->useBidSitioQuery()->filterByAreaProtegida(ProjectConfiguration::ANPPV)->endUse();
    }

    public function soloPimcpa() {
        return $this->useBidSitioQuery()->filterByAreaProtegida(ProjectConfiguration::PIMCPA)->endUse();
    }
    */
    public function soloAvesPlayerasPimcpa() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::AVES_PALYERAS_PIMCPA);
    }
    public function soloAvesPlayerasAnppv() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::AVES_PALYERAS_ANPPV);
    }
    public function soloMamiferosCarnivoros() {
        return $this->filterByIndicador(BidConteoIndicadorPeer::MAMIFEROS_CARNIVOROS);
    }
} // BidConteoIndicadorQuery
