<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_especie_relevancia' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Wed Mar 11 16:20:42 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidEspecieRelevanciaQuery extends BaseBidEspecieRelevanciaQuery
{
}
