<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_g1_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG1I1Peer extends BaseBidG1I1Peer {

    public static $ambientes=array(
        'i'=>'Intermareal',
        's'=>'Submareal'
    );
    /*
    public static $madureces= array(
        'm'=>'macho',
        'h'=>'hembra'
    );
    */
    public static $sexos_madureces = array(
        'mi'=>'macho inmaduro',
        'mm'=>'macho maduro y en evacuación',
        'hi'=>'hembra inmadura',
        'hm'=>'hembra maduración avanzada',
        'hd'=>'hembra en desove o desovada'
    );
    
} // BidG1I1Peer
