<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_g1_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG1I1Query extends BaseBidG1I1Query {

    public function indicadorActividadPesquera()
    {
        return $this->where('actividad_pesquera and  extract(month from fecha) in (12, 1, 2)')->count() > 0;
    }
    
    public function indicadorHembrasDesoveIntermareal() {
        return $this->filterByAmbiente('i')->filterBySexo('h')->filterByMadurez('d')->count() > 0;
    }
    public function indicadorGrupos() {
        return $this->select(array('sexo_madurez','s'))->groupBySexo()->groupByMadurez()->withColumn('sexo||madurez','sexo_madurez')->withColumn('count(*)','s');
    }
} // BidG1I1Query
