<?php



/**
 * Skeleton subclass for representing a row from the 'bid_g3_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG3I1 extends BaseBidG3I1 {

} // BidG3I1
