<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_g9_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG9I1Peer extends BaseBidG9I1Peer {

} // BidG9I1Peer
