<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_g5_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG5I1Query extends BaseBidG5I1Query {

    public function indicador() {
        return $this->select(array('ye','crias'))->withColumn("date_part('year', fecha )",'ye')->groupBy('ye')->orderBy('ye')->withColumn('sum(crias_destetadas)','crias');
    }
} // BidG5I1Query
