<?php



/**
 * Skeleton subclass for representing a row from the 'bid_g1_i1' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidG1I1 extends BaseBidG1I1 {

    public function getSexoMadurez()
    {
        return $this->sexo.$this->madurez;
    }

    public function setSexoMadurez($sm)
    {
        
//         echo substr($sm, 0,1);
//         echo '<br>';
//         echo substr($sm, 1,1);
//         echo '<br>';
//         echo $this->sexo;
//         echo '<br>';
//         echo $this->madurez;
//         $this->sexo=substr($sm, 0,1);
//         $this->madurez=substr($sm, 1,1);
        $this->setSexo(substr($sm, 0,1));
        $this->setMadurez(substr($sm, 1,1));
//         echo '<hr>';
//         echo $this->sexo;
//         echo '<br>';
//         echo $this->madurez;
//         die();
    }
} // BidG1I1
