<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bid_sitio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  2 11:22:16 2026
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BidSitioQuery extends BaseBidSitioQuery {

    public function metrosCuadradosPositivo()
    {
        return $this->where('st_area(the_geom)>0');
    }
} // BidSitioQuery
