<?php



/**
 * Skeleton subclass for representing a row from the 'canal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Apr 27 10:46:24 2023
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Canal extends BaseCanal {

} // Canal
