<?php



/**
 * Skeleton subclass for representing a row from the 'caudal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Nov 23 09:12:43 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Caudal extends BaseCaudal {

    public function getCaudalEmitido()
    {
        return $this->getCaudalVertido()+$this->getCaudalTurbinado();
    }
} // Caudal
