<?php



/**
 * Skeleton subclass for performing query and update operations on the 'credencial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Dec 14 19:16:26 2020
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class CredencialQuery extends BaseCredencialQuery {

} // CredencialQuery
