<?php



/**
 * Skeleton subclass for representing a row from the 'esquema' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jan  7 19:09:31 2025
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Esquema extends BaseEsquema {

    public function __toString() {
        return $this->getEsquemaRelatedByEsquemaId().'->'.$this->nombre;
    }
} // Esquema
