<?php



/**
 * Skeleton subclass for performing query and update operations on the 'girsu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jun 23 14:08:34 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class GirsuQuery extends BaseGirsuQuery {

} // GirsuQuery
