<?php



/**
 * Skeleton subclass for performing query and update operations on the 'girsu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jun 23 14:08:34 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class GirsuPeer extends BaseGirsuPeer {

    static public $tipos =array(
        1=>'BCA',
     //   2=>'Planta de Separacion/Relleno Sanitario/Basural',
        3=>'Planta de Separacion y Transferencia',
     //   4=>'Planta de Separacion y Transferencia /Relleno Sanitario',
     //   5=>'Planta de Transferencia',
        6=>'Relleno Sanitario',
     //   7=>'Planta de Separación y Transferencia /Basural',
        8=>'BCA saneado'
    );
} // GirsuPeer
