<?php



/**
 * Skeleton subclass for representing a row from the 'grupo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Dec 14 19:16:26 2020
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Grupo extends BaseGrupo {
    
    public function __toString()
    {
        return $this->descripcion;
    }
} // Grupo
