<?php



/**
 * Skeleton subclass for performing query and update operations on the 'kml' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jan 24 17:15:18 2023
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class KmlPeer extends BaseKmlPeer {

    const TIPO_ESCUELAS=1;
    const TIPO_CUENCAS=2;
    const TIPO_SUBCUENCAS=3;
    const TIPO_CUERPOS_DE_AGUA=4;
    const TIPO_COVERTURA_DE_SUELOS=5;
    const TIPO_AEROPUERTOS=6;
    const TIPO_PUERTOS=7;
    const TIPO_ALDEAS_PARAJES=8;
    const TIPO_LOCALIDADES=9;
    const TIPO_ESTANCIAS=10;
    const TIPO_ESTABLECIMIENTOS_RURALES=11;
    const TIPO_GENERADORES_ELECTRICOS=12;
    const TIPO_PARCELARIO_RURAL=13;
    const TIPO_DEPARTAMENTOS=14;
    const TIPO_RUTAS_NACIONALES=15;
    const TIPO_RUTAS_PROVINCIALES=16;
    const TIPO_EJIDOS_URBANOS=17;
    const TIPO_GANADERIA=18;
    const TIPO_GAS_ESTACIONES_REGULADORAS=19;
    const TIPO_GAS_CANERIAS_TGS=20;
    const TIPO_GAS_CANERIAS_AP=21;
    
    public static $tipos=array(
        self::TIPO_AEROPUERTOS=>'Aeropuertos',
        self::TIPO_ALDEAS_PARAJES=>'Aldeas y parajes',
        self::TIPO_DEPARTAMENTOS=>'Departamentos',
        self::TIPO_EJIDOS_URBANOS=>'Ejidos urbanos',
        self::TIPO_ESCUELAS=>'Escuelas',
        self::TIPO_ESTABLECIMIENTOS_RURALES=>'Establecimientos rurales',
        self::TIPO_ESTANCIAS=>'Estancias',
        self::TIPO_COVERTURA_DE_SUELOS=>'Covertura de suelos',
        self::TIPO_CUENCAS=>'Cuencas',
        self::TIPO_CUERPOS_DE_AGUA=>'Cuerpos de agua',
        self::TIPO_GENERADORES_ELECTRICOS=>'Generadores eléctricos',
        self::TIPO_LOCALIDADES=>'Localidades',
        self::TIPO_PARCELARIO_RURAL=>'Parcelario rural',
        self::TIPO_PUERTOS=>'Puertos',
        self::TIPO_RUTAS_NACIONALES=>'Rutas nacionales',
        self::TIPO_RUTAS_PROVINCIALES=>'Rutas provinciles',
        self::TIPO_SUBCUENCAS=>'Subcuencas',
        self::TIPO_GANADERIA=>'Ganadería',
        self::TIPO_GAS_ESTACIONES_REGULADORAS=>'Estaciones reguladoras de gas',
        self::TIPO_GAS_CANERIAS_TGS=>'Cañerías de gas de Transportadora Gas del Sur',
        self::TIPO_GAS_CANERIAS_AP=>'Cañerías de gas de alta presión',
        
   );
} // KmlPeer
