<?php



/**
 * Skeleton subclass for performing query and update operations on the 'kml' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jan 24 17:15:18 2023
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class KmlQuery extends BaseKmlQuery {

} // KmlQuery
