<?php



/**
 * Skeleton subclass for performing query and update operations on the 'localidad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jun  2 11:45:24 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LocalidadQuery extends BaseLocalidadQuery {
    
    protected function preSelect(PropelPDO $con)
    {
        if(!sfContext::getInstance()->getUser()->hasCredential('admin')){
            $locs= sfContext::getInstance()->getUser()->getLocalidades();
            if(count($locs)>0){
                $this->filterById($locs,Criteria::IN);
            }
        }
            
    }
    
} // LocalidadQuery
