<?php



/**
 * Skeleton subclass for performing query and update operations on the 'lugar_extraccion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Jan  4 13:29:12 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LugarExtraccionQuery extends BaseLugarExtraccionQuery {

    public function orderByLocalidad($o='asc')
    {
        return $this->useLocalidadQuery()->orderByNombre($o)->endUse();
    }
    

    public function orderByTipoMuestra($o='asc')
    {
        return $this->useTipoMuestraQuery()->orderByNombre($o)->endUse();
    }
    
    protected function preSelect(PropelPDO $con)
    {
        if(!sfContext::getInstance()->getUser()->hasCredential('admin')){
            
            $locs= sfContext::getInstance()->getUser()->getLocalidades();
            if(count($locs)>0){
                $this->filterByLocalidadId($locs,Criteria::IN);
            }
            $tipos= sfContext::getInstance()->getUser()->getTipos();
            if(count($tipos)>0){
                $this->filterByTipoId($tipos,Criteria::IN);
            }
        }
    }
    
    public function soloConAlgas()
    {
        return $this->useMuestraQuery()->filterByTaxa(null,Criteria::ISNOTNULL)->endUse();
    }
    
} // LugarExtraccionQuery
