<?php



/**
 * Skeleton subclass for representing a row from the 'lugar_extraccion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Jan  4 13:29:12 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LugarExtraccion extends BaseLugarExtraccion {

	public function __toString()
	{
		return $this->getLocalidad()->getNombre().' - '.$this->nombre;
		
	}

	public function conTipo()
	{
		return $this->getLocalidad()->getNombre().' - '.$this->nombre.( $this->tipo_id ? ' ('.$this->getTipoMuestra()->getNombre().')' : '');
		
	}
	
	public function getLocalizacion()
	{
	    $value = Dummy::geomToWkt($this->getTheGeom());
	    list ($lat, $lon) = Dummy::getLatLon(Dummy::getCentroid($value));
	    return Dummy::aGMS($lat, $lon);
	}
} // LugarExtraccion
