<?php



/**
 * Skeleton subclass for performing query and update operations on the 'mineria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Nov  3 09:25:16 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MineriaPeer extends BaseMineriaPeer {

    public static $categorias=array(
        '1era Categoría'=>array(
            'Exploración'=>array(
                13=>'Vigentes',
                1=>'Vencidos'
            ),
            'Explotación'=>array(
                2=>'Vigentes',
                3=>'Vencidos'
            )
        ),
        '2da Categoría'=>array(
            'Explotación'=>array(
                4=>'Vigentes',
                5=>'Vencidos'
            )
            
        ),
        '3era Categoría'=>array(
            'Áridos'=>array(
                6=>'Vigentes',
                7=>'Vencidos'
            ),
            'Pórfidos'=>array(
                8=>'Vigentes',
                9=>'Vencidos'
            ),
            'Calizas'=>array(
                10=>'Vigentes',
                11=>'Vencidos'
            ),
            12=>'Bancos en Río'
        )
    );
    protected static function recu($id,$estos){
        
        foreach ($estos as $k=>$values) {
            if( is_array($values)){
                $r=self::recu($id, $values);
                if($r) return $k.' '.$r;
            } elseif($k==$id) {
                return $values;
            }

        }
    }
    public static function categoria($id )
    {
        return self::recu($id,self::$categorias);
    }
} // MineriaPeer
