<?php



/**
 * Skeleton subclass for representing a row from the 'mineria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Nov  3 09:25:16 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Mineria extends BaseMineria {

} // Mineria
