<?php



/**
 * Skeleton subclass for performing query and update operations on the 'muestra' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Dec 14 17:46:19 2020
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MuestraQuery extends BaseMuestraQuery {

    
    public function filterByUso($v)
    {
        return $this->useLugarExtraccionQuery()->useLugarUsoQuery()->filterByUsoId($v)->endUse()->endUse();    
    }
    
    protected function preSelect(PropelPDO $con)
    {
        if(!sfContext::getInstance()->getUser()->hasCredential('admin')){
            $locs= sfContext::getInstance()->getUser()->getLocalidades();
            if(count($locs)>0){
                $this->useLugarExtraccionQuery()->filterByLocalidadId($locs,Criteria::IN)->endUse();
            }
            $tipos= sfContext::getInstance()->getUser()->getTipos();
            if(count($tipos)>0){
                $this->filterByTipoId($tipos,Criteria::IN);
            }
//             if(!sfContext::getInstance()->getUser()->hasCredential('muestra_ver_todas')){
//                 $this->filterByMostrar(true);
//             }
        }
    }
    
    public function filterByLocalidadId($lid) {
        return $this->useLugarExtraccionQuery()->filterByLocalidadId($lid)->endUse();
    }
    
    public function filterByTiposMezclados($v)
    {
        
        return $v? $this->where('lugar_extraccion.tipo_id !=muestra.tipo_id and lugar_extraccion.id is not null') : $this;
    }
    
    public function orderByTipoMuestra($o='asc') {
        return $this->useTipoMuestraQuery()->orderByNombre($o)->endUse();
    }
    
    
    public function orderByLugarExtraccion($o='asc') {
        return $this->useLugarExtraccionQuery()->useLocalidadQuery()->orderByNombre()->endUse()->orderByNombre($o)->endUse();
    }
    
    
    public function proximoNumero()
    {
        return 1+(int)$this->select('mn')->withColumn('max(numero)','mn')->findOne();
    }
    
    public function proximo()
    {
        return 1+(int)$this->select('pr')->withColumn('max(protocolo)','pr')->where('ye='.date('Y'))->findOne();
    }
    
    public function _orderByProtocolo($order=Criteria::ASC)
    {
        return parent::orderByProtocolo($order);
    }
    public function orderByProtocolo($order=Criteria::ASC)
    {
        return $this->orderByYe($order)->_orderByProtocolo($order);
    }
} // MuestraQuery
