<?php



/**
 * Skeleton subclass for representing a row from the 'parque_eolico' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Sep  3 10:42:04 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ParqueEolico extends BaseParqueEolico {

} // ParqueEolico
