<?php



/**
 * Skeleton subclass for representing a row from the 'responsable' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jun 30 14:41:46 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Responsable extends BaseResponsable {

    public function __toString()
    {
        return $this->nombre;
    }
} // Responsable
