<?php



/**
 * Skeleton subclass for performing query and update operations on the 'smart_observation_attributes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri May 23 11:49:23 2025
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SmartObservationAttributesPeer extends BaseSmartObservationAttributesPeer {

} // SmartObservationAttributesPeer
