<?php



/**
 * Skeleton subclass for performing query and update operations on the 'spatial_ref_sys' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Dec 17 10:35:06 2020
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SpatialRefSysPeer extends BaseSpatialRefSysPeer {

} // SpatialRefSysPeer
