<?php



/**
 * Skeleton subclass for representing a row from the 'tipo_muestra' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Nov  1 11:38:54 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TipoMuestra extends BaseTipoMuestra {

    public function __toString()
    {
        return $this->nombre;
    }
    
    public function getImagen()
    {
        if($this->archivo) return 'data:'.$this->getMime().';base64,'.base64_encode ( file_get_contents ( ProjectConfiguration::caminoIconoTipoMuesta(). $this->getArchivo() ) );
    }
    
} // TipoMuestra
