<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tipo_muestra' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Nov  1 11:38:54 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TipoMuestraQuery extends BaseTipoMuestraQuery {
    
    protected function preSelect(PropelPDO $con)
    {
        if(!sfContext::getInstance()->getUser()->hasCredential('admin')){
            
            $a= sfContext::getInstance()->getUser()->getTipos();
            if(count($a)>0){
                $this->filterById($a,Criteria::IN);
            }
        }
    }
} // TipoMuestraQuery
