<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tolerancia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Jan  8 19:13:10 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ToleranciaPeer extends BaseToleranciaPeer {

    static public function tipos()
    {
        $r= array();
        foreach (self::$campos as $i=>$t) $r[$i]= sfContext::getInstance()->getI18N()->__(sfInflector::humanize($t), array(), 'messages');
        return $r;
    }
    
    static $tipos = array(
        1=> 'Coliformes totales',
        2=> 'Coliformes fecales',
        3=> 'Escherichia Coli',
        4=> 'Enterococos Fecales',
        5=> 'Cloruros'
    );
    
    static $campos = array(
        1=> 'nmp_coliformes_totales_100',
        2=> 'nmp_coliformes_fecales_100',
        3=> 'nmp_escherichia_coli_100',
        4=> 'nmp_enterococos_fecales_100',
        5=> 'cloruros_mg_l',
    );
    
    static $campos_bactereologicos = array(
        1=> 'nmp_coliformes_totales_100',
        2=> 'nmp_coliformes_fecales_100',
        3=> 'nmp_escherichia_coli_100',
        4=> 'nmp_enterococos_fecales_100',
    );

} // ToleranciaPeer
