<?php



/**
 * Skeleton subclass for representing a row from the 'tolerancia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Jan  8 19:13:10 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Tolerancia extends BaseTolerancia {

} // Tolerancia
