<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tolerancia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Jan  8 19:13:10 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ToleranciaQuery extends BaseToleranciaQuery {

    public function maximo($tipo, $fecha) {
        $r=$this->filterByTipo($tipo)->filterByFecha($fecha, Criteria::LESS_EQUAL)->findOne();
        return $r ? $r->getMaximo() :null;
    }
    
    public function orderByUso($o='asc')
    {
        return $this->useUsoQuery()->orderByNombre($o)->endUse();
    }
} // ToleranciaQuery
