<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tratamiento' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Aug 30 11:00:47 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TratamientoPeer extends BaseTratamientoPeer {
    
    static public $tipos =array(
        5=>'Barro activado',
        1=>'Descarga',
        3=>'Humedal / Filtro fitoterrestre',
        6=>'Laguna aireada mecánicamente',
        4=>'Laguna de estabilización',
        2=>'Sistema anaeróbico'
    );
} // TratamientoPeer
