<?php



/**
 * Skeleton subclass for representing a row from the 'tratamiento' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Aug 30 11:00:47 2021
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Tratamiento extends BaseTratamiento {
    
    public function __toString()
    {
        return $this->nombre;
    }
} // Tratamiento
