<?php



/**
 * Skeleton subclass for representing a row from the 'uso' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Mar 18 08:54:41 2022
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Uso extends BaseUso {

    public function __toString()
    {
        return $this->nombre;
    }
} // Uso
