<?php



/**
 * Skeleton subclass for representing a row from the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Dec 14 19:16:26 2020
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Usuario extends BaseUsuario {

	public function __toString()
	{
		return $this->nombre;
	}
	
	
	public function resetAndEmail()
	{
	    
	    $p=Dummy::random(20);
	    
	    $this->setReset($p);
	    $this->save();
	    
 	    $i = sfContext::createInstance( ProjectConfiguration::getApplicationConfiguration('backend', 'prod', false) );
	    $t= "Acceda al siguiente vínculo para proporcionar la nueva clave del usuario <b>".$this->nombre."</b> para utilizar el sistema:\n\n".  preg_replace('/\/\w+\.php\//', '/backend.php/', $i->getController()->genUrl('usuario/check?reset='.$p, true));

	    $m = $i->getMailer()->compose(
	        ProjectConfiguration::EMAIL,
	        $this->email,
	        'Solicitud para restablecer clave de acceso - '.ProjectConfiguration::NOMBRE_ENTIDAD,
	        $t
        );
	    $m->addPart( nl2br( $t ), 'text/html' );
	    $i->getMailer()->send($m);
	    
	    
	}
	
	
} // Usuario
