indexSuccess:
  stylesheets: 
    - bid_indicadores_index
dataSuccess:
  has_layout: false
mapaSuccess:
  stylesheets: 
    - ../ol/ol.css
    - bid_mapaSuccess
  javascripts: 
    - ../ol/ol.js
    - ../ol/ol-layerswitcher.js
    - bid_mapaSuccess
  