generator:
  class: sfPropelGenerator
  param:
    model_class:           PromotorAmbiental
    theme:                 adminBS
    non_verbose_templates: true
    with_show:             false
    singular:              PromotorAmbiental
    plural:                PromotorAmbientals
    route_prefix:          promotor_ambiental
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        viejo:  
          label: Años anteriores
      list:    
        title: Promotores Ambientales
        batch_actions: {}
        object_actions: {}
        display:
          - =nombre
          - descripcion
          - viejo
      filter:  
        display:
          - nombre
      form:    ~
      edit:    
        title:  Modificar promotor ambiental
      new:     
        title:  Agregar promotor ambiental
